
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("820x465")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 465,
    width = 820,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    683.5,
    144.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#EAEAEA",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=579.0,
    y=131.0,
    width=209.0,
    height=25.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=576.0,
    y=403.0,
    width=216.0,
    height=41.0
)

canvas.create_rectangle(
    0.0,
    0.0,
    550.0,
    465.0,
    fill="#FF4646",
    outline="")

canvas.create_text(
    41.0,
    70.0,
    anchor="nw",
    text="Welcome to ApexAgente",
    fill="#FFFFFF",
    font=("MontserratRoman ExtraBold", 30 * -1)
)

canvas.create_rectangle(
    41.0,
    117.0,
    137.0,
    129.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    41.0,
    147.0,
    anchor="nw",
    text="We are a website that handle apex agent.",
    fill="#FFFFFF",
    font=("MontserratRoman Regular", 18 * -1)
)

canvas.create_text(
    41.0,
    170.0,
    anchor="nw",
    text="The way we work is to search through",
    fill="#FFFFFF",
    font=("MontserratRoman Regular", 18 * -1)
)

canvas.create_text(
    41.0,
    193.0,
    anchor="nw",
    text="hostname.",
    fill="#FFFFFF",
    font=("MontserratRoman Regular", 18 * -1)
)

canvas.create_text(
    599.0,
    77.0,
    anchor="nw",
    text="Enter credential",
    fill="#FF3131",
    font=("MontserratRoman Bold", 18 * -1)
)

canvas.create_text(
    580.0,
    117.0,
    anchor="nw",
    text="Host name",
    fill="#FF3131",
    font=("MontserratRoman Bold", 10 * -1)
)
window.resizable(False, False)
window.mainloop()
